#
obj-y  += msg2238a_ts.o
msg2238a_ts-objs += mstar_drv_sprd.o
msg2238a_ts-objs += mstar_drv_common.o
msg2238a_ts-objs += mstar_drv_utility_adaption.o
msg2238a_ts-objs += mstar_drv_fw_control.o
msg2238a_ts-objs += mstar_drv_mp_test.o
msg2238a_ts-objs += mstar_drv_ic_fw_porting_layer.o
msg2238a_ts-objs += mstar_drv_main.o
msg2238a_ts-objs += mstar_drv_platform_interface.o
msg2238a_ts-objs += mstar_drv_platform_porting_layer.o
msg2238a_ts-objs += mstar_drv_jni_interface.o
#
